### ISSUE TITLE
Server panics when connection to web3 server fails

### ISSUE THREAD

**Issue by ed255** [iden3/go-iden3-core#110]
Trace of the panic, with web3 server details redacted
```
+ exec go run main.go --config /tmp/iden3-test/server-configs/relayConfig.yaml start
INFO[0001] Keystore and account unlocked successfully    acc=0xZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ
INFO[0001] Connection to web3 server opened              url="http://XXX.XXX.XXX.XXX/YYYYYYYYYYYYYYYYYYYY"
INFO[0001] Storage opened                                path=/tmp/iden3-test/relay-treedb
INFO[0001] Current root                                  hash=0x0000000000000000000000000000000000000000000000000000000000000000
INFO[0001] Running claim service                         idAddr=0x0123456789abcdef0123456789abcdef01234567
PANI[0031] Post http://XXX.XXX.XXX.XXX/YYYYYYYYYYYYYYYYYYYY: dial tcp XXX.XXX.XXX.XXX:80: i/o timeout
panic: (*logrus.Entry) (0xe741e0,0xc000072720)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc000072180, 0xc000790030, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/dev/go/pkg/mod/github.com/sirupsen/logrus@v1.3.0/entry.go:227 +0x2ce
github.com/sirupsen/logrus.(*Entry).Log(0xc0000726c0, 0xc000000000, 0xc0001ab768, 0x1, 0x1)
        /home/dev/go/pkg/mod/github.com/sirupsen/logrus@v1.3.0/entry.go:256 +0xe4
github.com/sirupsen/logrus.(*Logger).Log(0xc000072180, 0x0, 0xc0001ab768, 0x1, 0x1)
        /home/dev/go/pkg/mod/github.com/sirupsen/logrus@v1.3.0/logger.go:184 +0x7f
github.com/sirupsen/logrus.(*Logger).Panic(...)
        /home/dev/go/pkg/mod/github.com/sirupsen/logrus@v1.3.0/logger.go:225
github.com/sirupsen/logrus.Panic(...)
        /home/dev/go/pkg/mod/github.com/sirupsen/logrus@v1.3.0/exported.go:123
github.com/iden3/go-iden3/cmd/relay/commands.cmdStart(0xc000286160, 0x0, 0xc000286160)
        /home/dev/git/iden3/go-iden3/cmd/relay/commands/server.go:56 +0x3f1
github.com/urfave/cli.HandleAction(0xd38820, 0xfd9248, 0xc000286160, 0xc000232400, 0x0)
        /home/dev/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xc8
github.com/urfave/cli.Command.Run(0xe84b61, 0x5, 0x0, 0x0, 0x17b6b00, 0x0, 0x0, 0xe8d18c, 0x10, 0x0, ...)
        /home/dev/go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x996
github.com/urfave/cli.(*App).Run(0xc00027c000, 0xc0000200c0, 0x4, 0x4, 0x0, 0x0)
        /home/dev/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x6af
main.main()
        /home/dev/git/iden3/go-iden3/cmd/relay/main.go:28 +0x536
exit status 2
```

**Comment by ed255** [comment]
fixed some time ago
